myproject/MyApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "first_app"

urlpatterns = [
    path( '',views.index, name="HomePage" ),
    path( 'add_album/',views.album_form, name="Album_Form" ),
    path( 'add_musician/',views.musician_form, name="Musician_Form" ),
    path( 'album_list/<int:artist_id>/',views.album_list, name="album_list" ),
    path( 'edit_artist/<int:artist_id>/',views.edit_artist, name="edit_artist" ),
    path( 'edit_album/<int:album_id>/',views.edit_album, name="edit_album" ),
    path( 'delete/<int:album_id>/',views.delete, name="delete" ),
    path( 'delete_artist/<int:artist_id>/',views.delete_aritst, name="delete_artist" ),


   
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyApp.urls'))
]

myproject/MyApp/models.py
from django.db import models

class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name
    

class Album(models.Model):
    artist = models.ForeignKey(Musician,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
   
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent")
    )
    num_stars = models.IntegerField(choices=rating)


    # class Meta:
    #     db_table ="album"



    def __str__(self):
        return str(self.name) + " " + str(self.num_stars)


 

myproject/MyApp/forms.py
from django import forms
from MyApp import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"


class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={
        'type':'date'
    }))
    class Meta:
        model = models.Album
        fields= "__all__"

myproject/MyApp/views.py
from django.shortcuts import render
from MyApp.models import *
from  MyApp import forms
from django.db.models import Avg ,Max
import time
 
def index(request):
    musician_list = Musician.objects.order_by("first_name")
    diction = {
        "title":"Home",
        "musician_list":musician_list
    }
    return render(request,'MyApp/index.html',context=diction)



def album_list(request,artist_id):
    artist_info = Musician.objects.get(pk =artist_id)
    album_list = Album.objects.filter(artist = artist_id).order_by('name', 'release_date')
    artist_rating = Album.objects.filter(artist = artist_id).aggregate(Avg("num_stars"))
    diction = {
        "title":"List Of Album",
        "artist_info":artist_info,
        "album_list": album_list,
        "artist_rating": artist_rating
    }
    return render(request,'MyApp/album_list.html',context=diction)

def musician_form(request):
    form = forms.MusicianForm()
    if request.method =="POST":
        form = forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {
        "title":"Add Musician",
        'musician_form':form
    }
    return render(request,'MyApp/musician_form.html',context=diction)

def album_form(request):
        
        form = forms.AlbumForm()
        if request.method =="POST":
            form = forms.AlbumForm(request.POST)
            if form.is_valid():
                form.save(commit=True)
                return index(request)
        diction = {
        "title":"Add Album",
        "album_form":form
         }
  
        return render(request,'MyApp/album_form.html',context=diction)


def edit_artist(request,artist_id):
     
     artist_info = Musician.objects.get(pk=artist_id)
     form = forms.MusicianForm(instance=artist_info)
     if request.method == "POST":
          form = forms.MusicianForm(request.POST, instance= artist_info)
          if form.is_valid():
               form.save(commit=True)
               return album_list(request,artist_id)

     diction = {
          'title':'EDIT ARTIST',
          'edit_form': form 
     }
     return render(request, 'MyApp/edit_artist.html', context=diction)



def edit_album(request,album_id):
     album_info = Album.objects.get(pk=album_id)
     form = forms.AlbumForm(instance=album_info)
     diction={}

     if request.method =="POST":
          form = forms.AlbumForm(request.POST,instance=album_info)
          if form.is_valid():
               form.save(commit=True)
               diction.update({"success_text":"Updated Successfully"})
               time.sleep(3)
               return album_list(request,album_id)
               
                
     diction.update( {
          
          'edit_form':form
     })
     diction.update({
          'album_id':album_id
     })
     return render(request, 'MyApp/edit_album.html',context=diction)

def delete(request,album_id):
     album = Album.objects.get(pk=album_id).delete()
     diction= {'delete_text':"Album deleted succesfully"}
     return render(request,'MyApp/delete.html',context=diction)

def delete_aritst(request,artist_id):
     artist = Musician.objects.get(pk=artist_id).delete()
     diction = {
          "delete_text":"Artist deleted succesfully"
     }
     return render(request,'MyApp/delete.html',context=diction)

myproject/templates/MyApp/album_form.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h2>This is Album List</h2>
<form action = " " method= "POST">
    {{album_form.as_p}}
    {% csrf_token %}
    <input type = "submit" name = "submit" value = "Add" class="btn btn-success ">
</form>
{% endblock body_block %}

myproject/templates/MyApp/album_list.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h2>This is Album List</h2>
{% comment %} {{artist_info}} {% endcomment %}
First Name = {{artist_info.first_name}} <br>
Last  Name = {{artist_info.last_name}}<br>
Instrument ={{artist_info.instrument}}<br>
Artist Raing = {{artist_rating.num_stars__avg}} <br>

{% comment %} <a href="{% url "first_app:edit_artist" artist_id = artist_info.id %}" class= "btn btn-success btn-sm"> EDIT </a> {% endcomment %}
{% comment %} <a href="{% url "first_app:edit_artist" artist_id = artist_info.id %}" class="btn btn-success btn-sm"> EDIT </a> {% endcomment %}
<a href='{% url "first_app:edit_artist" artist_id=artist_info.id %}' class="btn btn-success btn-sm"> EDIT </a>


 
<table class = "table table-border">
    <tr>
        <th> Album Name </th>
        <th> Releases Date </th>
        <th> Rating </th>
    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{% url 'first_app:edit_album' album_id=album.id %}">{{album.name}} </a></td>
        <td>{{album.release_date}}</td>
        <td>{{album.num_stars}}</td>
    </tr>
    
    {% endfor %}
</table>
<br>
<a href="{% url 'first_app:delete_artist' artist_id=artist_info.id %}" onclick="return alert("Wanna delete this Musician?")" class="btn btn-danger"> Delete</a>


 
{% endblock body_block %}

myproject/templates/MyApp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{title}}!</title>
  </head>
  <body>
    <section>
        <ul class="nav ">
            <li class="nav-item">
              <a class="nav-link active" href="{% url "first_app:HomePage" %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "first_app:Musician_Form" %}">Add Musician</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "first_app:Album_Form" %}">Add Album</a>
            </li>
             
          </ul>
    <section>

    <section>
        <div class="container">
            {% block body_block %}
            
            {% endblock body_block %}
        </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

myproject/templates/MyApp/delete.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h2 class= "alert alert-danger">{{delete_text}}</h2>
{% endblock body_block %}

myproject/templates/MyApp/edit_album.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h3> EDIT ALBUM NAME </h3>
 
{% if success_text %}

<div class="alert alert-success">{{success_text}}</div>
{% endif %}
<form method = "POST">
    {{edit_form.as_p}}
    {% csrf_token %}
    <input type = "submit" name = "submit" value = "Update" class= "btn btn-info">


</form>
<a href="{% url 'first_app:delete' album_id=album_id %}" class = "btn btn-danger mt-3" onclick="return confirm("Wanna delete this album?")"> Delete  </a>
{% endblock %}

myproject/templates/MyApp/edit_artist.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h4> EDIT ARTIST</h4>

<form action = "" method ="POST">
    {{edit_form.as_p}}
    {% csrf_token %}
    <input type = "submit" value= "Update"  class = "btn btn-info btn-sm" >
</form>
{% endblock body_block %}

myproject/templates/MyApp/index.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h2>This is Home Page</h2>

<ul>
{% if musician_list %}
    {% for musician in musician_list %}
        <li>
            <a href="{% url 'first_app:album_list' artist_id=musician.id %}">
                {{ musician.first_name }} {{ musician.last_name }}
            </a>
        </li>
    {% endfor %}
{% else %}
    <h3>No Musician to show</h3>
{% endif %}
</ul>

{% endblock body_block %}

myproject/templates/MyApp/musician_form.html
{% extends "MyApp/base.html" %}
{% block body_block %}
<h2> Musician Form</h2>
<form action = "" method = "POST">
    {{musician_form.as_p}}
    {% csrf_token %}
    <input type = "submit" name = "submit" value = "Add" class="btn btn-success ">
</form>
{% endblock body_block %}